[book]
title = "Introduction to Fluid Simulations"
author = "Quentin Wach"
description = "A hands-on guide to fluid simulations."

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
mathjax-support = true
